### PR TITLE
[permissions] output vs. panic

### PR DESCRIPTION
**Pull request by drew-u410**
* At present a `panic` will occur if permissions are not able to be fetched.
* It isn't clear to me (yet) why this can occur, but it does.  On a domain I ran this on with > 10k files, I got ~200 files in this case.
* Allows the process to proceed, and output the list for review.

### CODE REVIEW

**Comment by jgimenez** [comment]
Thanks for your contribution. I'm not sure I like, however, to keep going if there has been an error. I'd rather make it fail if something went wrong. Maybe if there's a reason for these requests to fail, the underlying reason could be fixed instead.

**Comment by drew-u410** [comment]
Agreed- still investigating.

I definitely still wanted the data, in my case.

Assuming I can find the issue, happy to propose a fix.

**Comment by fk-storyblok** [comment]
hey Folks - same here - getting 'did not get any file permissions:' and an empty output file, which defeats the purpose of the tool. @drew-u410 - does your pull request fix this? (i assume yes)

**Comment by jgimenez** [comment]
This has been inactive for 2 years, so I'm closing it. Please feel free to reopen.

**Pull request closed without merging**
